export interface ActionStep {
  id: string
  title: string
  description: string
  icon: string
  completed: boolean
  required: boolean
  estimatedTime: string
  helpText?: string
  linkTo?: string
}

export interface ActionFlow {
  id: string
  title: string
  description: string
  category: "onboarding" | "daily" | "weekly" | "setup" | "recovery"
  steps: ActionStep[]
  totalTime: string
  priority: "high" | "medium" | "low"
}

export const ACTION_FLOWS: ActionFlow[] = [
  {
    id: "daily-routine",
    title: "Daily Trading Routine",
    description: "Your essential daily checklist for consistent trading success",
    category: "daily",
    totalTime: "15-20 min",
    priority: "high",
    steps: [
      {
        id: "morning-check",
        title: "Morning Readiness Check",
        description: "Complete your morning assessment",
        icon: "☀️",
        completed: false,
        required: true,
        estimatedTime: "5 min",
        helpText: "Track sleep, routine, and mental readiness before trading",
        linkTo: "/morning-check",
      },
      {
        id: "review-plan",
        title: "Review Trading Plan",
        description: "Read your trading rules and strategy",
        icon: "📋",
        completed: false,
        required: true,
        estimatedTime: "3 min",
        helpText: "Refresh your memory on entry/exit rules",
      },
      {
        id: "check-readiness",
        title: "Check Readiness Score",
        description: "Verify you're >60% ready to trade",
        icon: "🎯",
        completed: false,
        required: true,
        estimatedTime: "1 min",
        helpText: "If below 60%, consider skipping trading today",
        linkTo: "/morning-check",
      },
      {
        id: "pre-trade-journal",
        title: "Pre-Trade Journal",
        description: "Write your intentions for today",
        icon: "✍️",
        completed: false,
        required: false,
        estimatedTime: "5 min",
        helpText: "What's your focus? What will you avoid?",
        linkTo: "/journal",
      },
      {
        id: "evening-review",
        title: "Evening Review",
        description: "Journal your trades and lessons",
        icon: "🌙",
        completed: false,
        required: true,
        estimatedTime: "10 min",
        helpText: "Log all trades with emotions and learnings",
        linkTo: "/journal",
      },
    ],
  },
  {
    id: "first-setup",
    title: "Initial Setup",
    description: "Get started with MindTrader - one-time configuration",
    category: "setup",
    totalTime: "30 min",
    priority: "high",
    steps: [
      {
        id: "complete-profile",
        title: "Complete Your Profile",
        description: "Set up your trading style and experience",
        icon: "👤",
        completed: false,
        required: true,
        estimatedTime: "5 min",
        helpText: "Go to Account → Profile tab",
        linkTo: "/account",
      },
      {
        id: "set-trading-settings",
        title: "Configure Trading Settings",
        description: "Choose your style, risk level, and timezone",
        icon: "⚙️",
        completed: false,
        required: true,
        estimatedTime: "5 min",
        helpText: "Account → Trading tab → Set your preferences",
        linkTo: "/account",
      },
      {
        id: "add-first-challenge",
        title: "Add Prop Firm Challenge (Optional)",
        description: "Track your funded account or challenge",
        icon: "🏢",
        completed: false,
        required: false,
        estimatedTime: "5 min",
        helpText: "Account → Trading → Add Challenge",
        linkTo: "/account",
      },
      {
        id: "first-daily-entry",
        title: "Complete First Daily Entry",
        description: "Fill out your baseline Daily Tracker",
        icon: "📊",
        completed: false,
        required: true,
        estimatedTime: "10 min",
        helpText: "Daily Tracker → Fill all sections honestly",
        linkTo: "/daily-tracker",
      },
      {
        id: "explore-mindtrader",
        title: "Chat with MindTrader AI",
        description: "Ask your first question to the AI coach",
        icon: "🧠",
        completed: false,
        required: false,
        estimatedTime: "5 min",
        helpText: 'Try "How do I recover after a loss?"',
        linkTo: "/mindtrader",
      },
    ],
  },
  {
    id: "weekly-review",
    title: "Weekly Review Process",
    description: "Reflect on your week and plan improvements",
    category: "weekly",
    totalTime: "45 min",
    priority: "medium",
    steps: [
      {
        id: "calculate-stats",
        title: "Review Weekly Stats",
        description: "Check your win rate, P&L, and consistency",
        icon: "📈",
        completed: false,
        required: true,
        estimatedTime: "10 min",
        helpText: "Analytics → Check all metrics",
        linkTo: "/analytics",
      },
      {
        id: "journal-review",
        title: "Read All Journal Entries",
        description: "Review your daily journals from the week",
        icon: "📖",
        completed: false,
        required: true,
        estimatedTime: "15 min",
        helpText: "Journal → Calendar view → Read each day",
        linkTo: "/journal",
      },
      {
        id: "identify-patterns",
        title: "Identify Patterns",
        description: "What emotions led to wins/losses?",
        icon: "🔍",
        completed: false,
        required: true,
        estimatedTime: "10 min",
        helpText: "Look for recurring emotional triggers",
      },
      {
        id: "set-goals",
        title: "Set Next Week's Goals",
        description: "1-3 specific, measurable goals",
        icon: "🎯",
        completed: false,
        required: true,
        estimatedTime: "5 min",
        helpText: "Example: Reduce revenge trades to 0",
      },
      {
        id: "ai-insights",
        title: "Get AI Insights",
        description: "Ask MindTrader AI for weekly analysis",
        icon: "🤖",
        completed: false,
        required: false,
        estimatedTime: "5 min",
        helpText: "MindTrader → Generate Insights",
        linkTo: "/mindtrader",
      },
    ],
  },
  {
    id: "loss-recovery",
    title: "Loss Recovery Protocol",
    description: "Steps to take immediately after a significant loss",
    category: "recovery",
    totalTime: "2+ hours",
    priority: "high",
    steps: [
      {
        id: "stop-trading",
        title: "STOP TRADING",
        description: "Close platform immediately",
        icon: "🛑",
        completed: false,
        required: true,
        estimatedTime: "1 min",
        helpText: "No revenge trades. Period.",
      },
      {
        id: "breathe",
        title: "Breathing Exercise",
        description: "4-7-8 breathing for 5 minutes",
        icon: "🫁",
        completed: false,
        required: true,
        estimatedTime: "5 min",
        helpText: "4s inhale, 7s hold, 8s exhale. Repeat 10x.",
      },
      {
        id: "journal-loss",
        title: "Journal the Loss",
        description: "Write exactly what happened and how you feel",
        icon: "📝",
        completed: false,
        required: true,
        estimatedTime: "15 min",
        helpText: "Be brutally honest with yourself",
        linkTo: "/journal",
      },
      {
        id: "walk-away",
        title: "Physical Activity",
        description: "Go for a walk or exercise",
        icon: "🚶",
        completed: false,
        required: true,
        estimatedTime: "30 min",
        helpText: "Get away from screens completely",
      },
      {
        id: "talk-to-ai",
        title: "Chat with MindTrader AI",
        description: "Process emotions with AI coach",
        icon: "💬",
        completed: false,
        required: true,
        estimatedTime: "10 min",
        helpText: "Ask: 'I just had a big loss, help me process this'",
        linkTo: "/mindtrader",
      },
      {
        id: "minimum-break",
        title: "Minimum 2 Hour Break",
        description: "Do NOT trade for at least 2 hours",
        icon: "⏰",
        completed: false,
        required: true,
        estimatedTime: "120+ min",
        helpText: "Better yet, skip rest of the day",
      },
      {
        id: "readiness-check",
        title: "Check Readiness Tomorrow",
        description: "Review readiness before trading again",
        icon: "✅",
        completed: false,
        required: true,
        estimatedTime: "5 min",
        helpText: "Must be >70% to trade again",
        linkTo: "/morning-check",
      },
    ],
  },
  {
    id: "new-challenge-setup",
    title: "New Prop Firm Challenge Setup",
    description: "Start tracking a new prop firm account properly",
    category: "setup",
    totalTime: "20 min",
    priority: "medium",
    steps: [
      {
        id: "add-challenge",
        title: "Add Challenge Details",
        description: "Enter firm name, balance, rules",
        icon: "🏢",
        completed: false,
        required: true,
        estimatedTime: "5 min",
        helpText: "Account → Trading → Add Challenge",
        linkTo: "/account",
      },
      {
        id: "set-active",
        title: "Set as Active Challenge",
        description: "Make this your current trading account",
        icon: "✅",
        completed: false,
        required: true,
        estimatedTime: "1 min",
        helpText: "Click 'Set Active' on the challenge",
        linkTo: "/account",
      },
      {
        id: "review-rules",
        title: "Review Challenge Rules",
        description: "Note daily loss limit, profit target, etc.",
        icon: "📋",
        completed: false,
        required: true,
        estimatedTime: "5 min",
        helpText: "Write rules in challenge notes",
      },
      {
        id: "create-plan",
        title: "Create Trading Plan",
        description: "Define your strategy for this challenge",
        icon: "📝",
        completed: false,
        required: true,
        estimatedTime: "10 min",
        helpText: "Journal → Create 'Challenge Strategy' entry",
        linkTo: "/journal",
      },
    ],
  },
]
