import { NextResponse } from "next/server"

export async function POST(request: Request) {
  try {
    const { trades, journals, moodHistory, period } = await request.json()

    const report = generateReport(trades, journals, moodHistory, period)

    return NextResponse.json({ report })
  } catch (error) {
    console.error("Error generating report:", error)
    return NextResponse.json({ error: "Failed to generate report" }, { status: 500 })
  }
}

function generateReport(trades: any[], journals: any[], moodHistory: any[], period: string) {
  const report = []

  report.push(`# MindTrader AI ${period === "weekly" ? "Weekly" : "Monthly"} Report`)
  report.push(`Generated: ${new Date().toLocaleDateString()}`)
  report.push(`\n---\n`)

  // Performance Summary
  report.push(`## 📊 Performance Summary`)
  const totalTrades = trades.length
  const winningTrades = trades.filter((t) => (t.pnl || 0) > 0).length
  const losingTrades = trades.filter((t) => (t.pnl || 0) < 0).length
  const totalPnL = trades.reduce((sum, t) => sum + (t.pnl || 0), 0)
  const winRate = totalTrades > 0 ? (winningTrades / totalTrades) * 100 : 0

  report.push(`- **Total Trades:** ${totalTrades}`)
  report.push(`- **Winning Trades:** ${winningTrades}`)
  report.push(`- **Losing Trades:** ${losingTrades}`)
  report.push(`- **Win Rate:** ${winRate.toFixed(1)}%`)
  report.push(`- **Total P&L:** $${totalPnL.toFixed(2)}`)

  // Psychological Insights
  report.push(`\n## 🧠 Psychological Insights`)
  const avgMood = moodHistory.reduce((sum, m) => sum + m.mood, 0) / (moodHistory.length || 1)
  const avgConfidence = moodHistory.reduce((sum, m) => sum + m.confidence, 0) / (moodHistory.length || 1)
  const avgStress = moodHistory.reduce((sum, m) => sum + m.stress, 0) / (moodHistory.length || 1)

  report.push(`- **Average Mood:** ${avgMood.toFixed(1)}/10`)
  report.push(`- **Average Confidence:** ${avgConfidence.toFixed(1)}/10`)
  report.push(`- **Average Stress:** ${avgStress.toFixed(1)}/10`)

  // Top Patterns
  report.push(`\n## 🔍 Behavior Patterns`)

  if (avgMood < 6 && winRate < 50) {
    report.push(`- ⚠️ Low mood correlates with lower win rate`)
    report.push(`- **Recommendation:** Focus on mood management before trading`)
  }

  if (avgStress > 7) {
    report.push(`- ⚠️ High stress levels detected throughout the period`)
    report.push(`- **Recommendation:** Implement stress reduction techniques`)
  }

  // Journal Insights
  if (journals.length > 0) {
    report.push(`\n## 📝 Journal Activity`)
    report.push(`- **Total Journal Entries:** ${journals.length}`)
    const tradeEntries = journals.filter((j) => j.type === "trade").length
    const reflectionEntries = journals.filter((j) => j.type === "journal").length
    report.push(`- **Trade Entries:** ${tradeEntries}`)
    report.push(`- **Reflection Entries:** ${reflectionEntries}`)
  }

  // Action Plan
  report.push(`\n## 🎯 Action Plan for Next Period`)
  if (winRate < 50) {
    report.push(`1. Reduce trading frequency - focus on A+ setups only`)
    report.push(`2. Review and update your trading plan`)
    report.push(`3. Practice paper trading to rebuild confidence`)
  } else if (winRate >= 70) {
    report.push(`1. Maintain current discipline - it's working!`)
    report.push(`2. Document your process for consistency`)
    report.push(`3. Consider gradually scaling position size`)
  } else {
    report.push(`1. Continue current approach with minor tweaks`)
    report.push(`2. Focus on risk management and position sizing`)
    report.push(`3. Keep detailed trade journals`)
  }

  if (avgMood < 6) {
    report.push(`4. Prioritize mental health and well-being`)
    report.push(`5. Consider consulting a trading psychologist`)
  }

  report.push(`\n---\n`)
  report.push(`*This report was generated by MindTrader AI based on your trading data and psychological metrics.*`)

  return report.join("\n")
}
