// Demo Data Generator
// Creates realistic demo data for testing

export function generateDemoData() {
  // Generate demo trades with realistic data
  const demoTrades = [
    {
      id: "demo-trade-1",
      date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      symbol: "EURUSD",
      type: "long",
      entryPrice: 1.095,
      exitPrice: 1.098,
      quantity: 1.0,
      pnl: 300,
      riskRewardRatio: 2.5,
      followedPlan: true,
      emotionBefore: "Klidný",
      emotionDuring: "Sebevědomý",
      emotionAfter: "Spokojený",
      confidenceBefore: 80,
      stressLevel: 20,
      mood: "Dobrá",
      notes: "Perfektní setup podle plánu",
    },
    {
      id: "demo-trade-2",
      date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      symbol: "GBPUSD",
      type: "short",
      entryPrice: 1.265,
      exitPrice: 1.267,
      quantity: 1.0,
      pnl: -200,
      riskRewardRatio: 1.5,
      followedPlan: false,
      emotionBefore: "Nervózní",
      emotionDuring: "Stresovaný",
      emotionAfter: "Zklamaný",
      confidenceBefore: 50,
      stressLevel: 70,
      mood: "Špatná",
      notes: "Impulzivní vstup bez potvrzení",
    },
    {
      id: "demo-trade-3",
      date: new Date().toISOString(),
      symbol: "USDJPY",
      type: "long",
      entryPrice: 148.5,
      exitPrice: 149.0,
      quantity: 1.0,
      pnl: 500,
      riskRewardRatio: 3.0,
      followedPlan: true,
      emotionBefore: "Sebevědomý",
      emotionDuring: "Klidný",
      emotionAfter: "Nadšený",
      confidenceBefore: 90,
      stressLevel: 10,
      mood: "Výborná",
      notes: "Skvělý breakout trade",
    },
  ]

  // Generate demo morning checks
  const demoMorningChecks = [
    {
      id: "demo-morning-1",
      date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      sleepQuality: 8,
      sleepHours: 7.5,
      energyLevel: 8,
      stressLevel: 3,
      focus: 8,
      physicalHealth: 9,
      emotionalState: 8,
      exercise: true,
      exerciseMinutes: 30,
      meditation: true,
      meditationMinutes: 15,
      morningRoutine: true,
      hydration: true,
      score: 85,
    },
    {
      id: "demo-morning-2",
      date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      sleepQuality: 6,
      sleepHours: 5.5,
      energyLevel: 5,
      stressLevel: 6,
      focus: 5,
      physicalHealth: 7,
      emotionalState: 5,
      exercise: false,
      exerciseMinutes: 0,
      meditation: false,
      meditationMinutes: 0,
      morningRoutine: false,
      hydration: true,
      score: 58,
    },
    {
      id: "demo-morning-3",
      date: new Date().toISOString().split("T")[0],
      sleepQuality: 9,
      sleepHours: 8,
      energyLevel: 9,
      stressLevel: 2,
      focus: 9,
      physicalHealth: 9,
      emotionalState: 9,
      exercise: true,
      exerciseMinutes: 45,
      meditation: true,
      meditationMinutes: 20,
      morningRoutine: true,
      hydration: true,
      score: 92,
    },
  ]

  // Generate demo gamification data
  const demoGamification = {
    xp: 450,
    level: 3,
    achievements: [
      {
        id: "first-trade",
        name: "První obchod",
        description: "Zaznamenejte svůj první obchod",
        unlocked: true,
        unlockedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "morning-streak-3",
        name: "Ranní rutina - 3 dny",
        description: "Dokončete morning check 3 dny v řadě",
        unlocked: true,
        unlockedAt: new Date().toISOString(),
      },
    ],
    dailyXPLog: {},
  }

  return {
    trades: demoTrades,
    morningChecks: demoMorningChecks,
    gamification: demoGamification,
  }
}
