// Demo Data Generator
// Creates realistic demo data for testing

// Helper function to generate 30 days of diverse demo trades
function generate30DaysTrades() {
  const pairs = ["EURUSD", "GBPUSD", "USDJPY", "XAUUSD", "BTCUSD", "AUDUSD", "NZDUSD", "EURJPY"]
  const setups = [
    "Breakout z konsolidace",
    "Support retest",
    "Resistance rejection",
    "Trend continuation",
    "Reversal pattern",
    "Range trading",
    "News trading"
  ]
  const timeframes = ["M15", "M30", "H1", "H4", "D1"]
  
  const trades = []
  
  for (let i = 0; i < 30; i++) {
    const isWin = Math.random() > 0.4 // 60% win rate
    const pair = pairs[Math.floor(Math.random() * pairs.length)]
    const direction = Math.random() > 0.5 ? "long" : "short"
    const pnl = isWin ? Math.floor(Math.random() * 1500) + 200 : -Math.floor(Math.random() * 800) - 100
    const followedPlan = Math.random() > 0.3 // 70% followed plan
    const mood = isWin ? Math.floor(Math.random() * 30) + 70 : Math.floor(Math.random() * 40) + 30
    
    trades.push({
      id: `demo-trade-generated-${i}`,
      date: new Date(Date.now() - i * 24 * 60 * 60 * 1000).toISOString(),
      pair: pair,
      symbol: pair,
      direction: direction,
      type: direction,
      entryPrice: Math.random() * 100 + 1,
      exitPrice: Math.random() * 100 + 1,
      quantity: Math.random() * 2 + 0.5,
      lotSize: Math.random() * 2 + 0.5,
      pnl: pnl,
      profitLoss: pnl,
      riskRewardRatio: isWin ? Math.random() * 2 + 1.5 : Math.random() * 1.5 + 0.5,
      stopLoss: Math.random() * 100,
      takeProfit: Math.random() * 100,
      followedPlan: followedPlan,
      matchedPlan: followedPlan,
      emotionBefore: isWin ? "Confident" : Math.random() > 0.5 ? "Nervous" : "Anxious",
      emotionDuring: isWin ? "Calm" : "Stressful",
      emotionAfter: isWin ? "Satisfied" : "Disappointed",
      confidenceBefore: Math.floor(Math.random() * 40) + (isWin ? 60 : 30),
      confidence: Math.floor(Math.random() * 40) + (isWin ? 60 : 30),
      stressLevel: Math.floor(Math.random() * 40) + (isWin ? 10 : 50),
      stress: Math.floor(Math.random() * 40) + (isWin ? 10 : 50),
      mood: mood,
      discipline: followedPlan ? Math.floor(Math.random() * 20) + 75 : Math.floor(Math.random() * 40) + 30,
      entryTime: `${String(Math.floor(Math.random() * 8) + 8).padStart(2, '0')}:${String(Math.floor(Math.random() * 60)).padStart(2, '0')}`,
      exitTime: `${String(Math.floor(Math.random() * 8) + 10).padStart(2, '0')}:${String(Math.floor(Math.random() * 60)).padStart(2, '0')}`,
      duration: Math.floor(Math.random() * 400) + 30,
      entryReason: setups[Math.floor(Math.random() * setups.length)] + " + " + (Math.random() > 0.5 ? "volume spike" : "confluence"),
      exitReason: isWin ? (Math.random() > 0.5 ? "Take profit hit" : "Trailed stop") : "Stop loss hit",
      marketConditions: Math.random() > 0.5 ? "Trending market" : "Range-bound market",
      setup: setups[Math.floor(Math.random() * setups.length)],
      timeframe: timeframes[Math.floor(Math.random() * timeframes.length)],
      tags: isWin ? ["profitable", followedPlan ? "followed plan" : "impulsive"] : ["loss", followedPlan ? "good execution" : "mistake"],
      notes: isWin ? "Trade skončil profitem." : "Trade skončil ztrátou.",
      whatWorked: isWin ? "Entry timing byl dobrý" : "N/A",
      whatDidntWork: isWin ? "N/A" : "Setup nevyšel",
      lessons: [isWin ? "Pokračovat v tomto přístupu" : "Zlepšit vstup"],
      mistakes: followedPlan ? [] : ["Nedodržel jsem plán"],
      improvements: ["Další iterace strategie"],
      screenshot: null,
      revengeTrade: !followedPlan && Math.random() > 0.7,
      exitedEarly: isWin && Math.random() > 0.8,
      missedDueToHesitation: false,
      commission: Math.random() * 5 + 2,
      riskAmount: Math.abs(pnl) * 0.5,
      rewardAmount: Math.abs(pnl) * (isWin ? 1 : 2),
      winRate: isWin ? 100 : 0,
    })
  }
  
  return trades
}

export function generateDemoData() {
  // Generate demo trades with realistic data - 30 days of trades
  const demoTrades = [
    {
      id: "demo-trade-1",
      date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      pair: "EURUSD",
      symbol: "EURUSD",
      direction: "long",
      type: "long",
      entryPrice: 1.095,
      exitPrice: 1.098,
      quantity: 2.0,
      lotSize: 2.0,
      pnl: 600,
      profitLoss: 600,
      riskRewardRatio: 2.5,
      stopLoss: 1.092,
      takeProfit: 1.100,
      followedPlan: true,
      matchedPlan: true,
      emotionBefore: "Klidný",
      emotionDuring: "Sebevědomý",
      emotionAfter: "Spokojený",
      confidenceBefore: 80,
      confidence: 80,
      stressLevel: 20,
      stress: 20,
      mood: 85,
      discipline: 90,
      entryTime: "08:30",
      exitTime: "12:45",
      duration: 255,
      entryReason: "Breakout z ranžu + konfluence s denním supportem",
      exitReason: "Take profit hit podle plánu",
      marketConditions: "Volatilní London open, trending market",
      setup: "Bullish engulfing + support retest",
      timeframe: "H1",
      tags: ["A+ setup", "trend following", "high conviction"],
      notes: "Perfektní setup podle plánu. Trpělivě jsem čekal na potvrzení.",
      whatWorked: "Čekal jsem na pullback k supportu místo chase",
      whatDidntWork: "N/A",
      lessons: ["Trpělivost se vyplatila", "Confluence zvyšuje win rate"],
      mistakes: [],
      improvements: ["Příště zkusit držet pozici déle pro větší RR"],
      screenshot: null,
      revengeTrade: false,
      exitedEarly: false,
      missedDueToHesitation: false,
      commission: 4.5,
      riskAmount: 240,
      rewardAmount: 600,
      winRate: 100,
    },
    {
      id: "demo-trade-2",
      date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      pair: "GBPUSD",
      symbol: "GBPUSD",
      direction: "short",
      type: "short",
      entryPrice: 1.265,
      exitPrice: 1.267,
      quantity: 1.5,
      lotSize: 1.5,
      pnl: -300,
      profitLoss: -300,
      riskRewardRatio: 1.5,
      stopLoss: 1.268,
      takeProfit: 1.260,
      followedPlan: false,
      matchedPlan: false,
      emotionBefore: "Nervózní",
      emotionDuring: "Stresovaný",
      emotionAfter: "Zklamaný",
      confidenceBefore: 50,
      confidence: 50,
      stressLevel: 70,
      stress: 70,
      mood: 45,
      discipline: 40,
      entryTime: "15:20",
      exitTime: "15:45",
      duration: 25,
      entryReason: "FOMO po velkém pohybu, bez potvrzení",
      exitReason: "Stop loss hit",
      marketConditions: "Choppy, low volume afternoon",
      setup: "Weak reversal pattern",
      timeframe: "M15",
      tags: ["FOMO", "impulsive", "bad timing"],
      notes: "Impulzivní vstup bez potvrzení. Neměl jsem tradovat odpoledne.",
      whatWorked: "N/A",
      whatDidntWork: "Trading mimo prime time, žádná konfluence",
      lessons: ["Netradovat v low volume periodech", "Čekat na setup, ne ho honit"],
      mistakes: ["FOMO entry", "Trading mimo moje časové okno", "Nerespektoval stop loss zónu"],
      improvements: ["Držet se trading plánu", "Netradovat po 14:00"],
      screenshot: null,
      revengeTrade: false,
      exitedEarly: false,
      missedDueToHesitation: false,
      commission: 3.5,
      riskAmount: 300,
      rewardAmount: 450,
      winRate: 0,
    },
    {
      id: "demo-trade-3",
      date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      pair: "USDJPY",
      symbol: "USDJPY",
      direction: "long",
      type: "long",
      entryPrice: 148.5,
      exitPrice: 149.2,
      quantity: 3.0,
      lotSize: 3.0,
      pnl: 1400,
      profitLoss: 1400,
      riskRewardRatio: 3.0,
      stopLoss: 148.0,
      takeProfit: 150.0,
      followedPlan: true,
      matchedPlan: true,
      emotionBefore: "Sebevědomý",
      emotionDuring: "Klidný",
      emotionAfter: "Nadšený",
      confidenceBefore: 90,
      confidence: 90,
      stressLevel: 10,
      stress: 10,
      mood: 95,
      discipline: 95,
      entryTime: "09:15",
      exitTime: "14:30",
      duration: 315,
      entryReason: "Breakout z konsolidace + volume spike",
      exitReason: "Moved stop to breakeven, trailed stop hit",
      marketConditions: "Strong trending market, high volume",
      setup: "Bull flag breakout",
      timeframe: "H4",
      tags: ["breakout", "high conviction", "A+ setup"],
      notes: "Skvělý breakout trade s perfektním timingem. Trpělivě jsem čekal na pullback.",
      whatWorked: "Entry timing, trailing stop strategy",
      whatDidntWork: "Mohl jsem držet déle, exited trochu brzy",
      lessons: ["Trailing stop funguje skvěle", "Breakouty v ranních hodinách mají vyšší follow-through"],
      mistakes: [],
      improvements: ["Zkusit držet pozici do konce dne při silném trendu"],
      screenshot: null,
      revengeTrade: false,
      exitedEarly: true,
      missedDueToHesitation: false,
      commission: 6.0,
      riskAmount: 500,
      rewardAmount: 1500,
      winRate: 100,
    },
    {
      id: "demo-trade-4",
      date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      pair: "XAUUSD",
      symbol: "XAUUSD",
      direction: "short",
      type: "short",
      entryPrice: 2340,
      exitPrice: 2310,
      quantity: 0.5,
      lotSize: 0.5,
      pnl: 1500,
      profitLoss: 1500,
      riskRewardRatio: 4.0,
      stopLoss: 2355,
      takeProfit: 2280,
      followedPlan: true,
      matchedPlan: true,
      emotionBefore: "Focused",
      emotionDuring: "Patient",
      emotionAfter: "Satisfied",
      confidenceBefore: 85,
      confidence: 85,
      stressLevel: 25,
      stress: 25,
      mood: 88,
      discipline: 92,
      entryTime: "10:00",
      exitTime: "16:45",
      duration: 405,
      entryReason: "Rejection z resistance + bearish divergence na RSI",
      exitReason: "Partial TP hit, moved rest to BE",
      marketConditions: "Range-bound with clear S/R levels",
      setup: "Resistance rejection + divergence",
      timeframe: "H1",
      tags: ["range trading", "divergence", "planned"],
      notes: "Perfektní rejection z resistance. Použil jsem partial profit strategy.",
      whatWorked: "Patience při vstupu, partial TP strategy",
      whatDidntWork: "N/A",
      lessons: ["Partial profit taking snižuje stress", "Divergence + S/R = vysoká pravděpodobnost"],
      mistakes: [],
      improvements: [],
      screenshot: null,
      revengeTrade: false,
      exitedEarly: false,
      missedDueToHesitation: false,
      commission: 3.0,
      riskAmount: 375,
      rewardAmount: 1500,
      winRate: 100,
    },
    {
      id: "demo-trade-5",
      date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      pair: "BTCUSD",
      symbol: "BTCUSD",
      direction: "long",
      type: "long",
      entryPrice: 67500,
      exitPrice: 66800,
      quantity: 0.1,
      lotSize: 0.1,
      pnl: -700,
      profitLoss: -700,
      riskRewardRatio: 2.0,
      stopLoss: 66500,
      takeProfit: 69500,
      followedPlan: true,
      matchedPlan: true,
      emotionBefore: "Confident",
      emotionDuring: "Anxious",
      emotionAfter: "Disappointed but accepting",
      confidenceBefore: 75,
      confidence: 75,
      stressLevel: 60,
      stress: 60,
      mood: 55,
      discipline: 85,
      entryTime: "13:30",
      exitTime: "14:15",
      duration: 45,
      entryReason: "Support retest + bullish momentum",
      exitReason: "Stop loss hit - market reversed",
      marketConditions: "Volatile, news-driven movement",
      setup: "Failed support retest",
      timeframe: "H1",
      tags: ["loss", "followed plan", "stopped out"],
      notes: "Trade podle plánu, ale trh šel proti mně. Akceptuji ztrátu.",
      whatWorked: "Respektoval jsem stop loss",
      whatDidntWork: "Entry timing - měl jsem počkat na potvrzení",
      lessons: ["Ne každý dobrý setup vyjde", "Stop loss mi zachránil účet"],
      mistakes: ["Entry trochu předčasný"],
      improvements: ["Počkat na extra potvrzení v volatilních podmínkách"],
      screenshot: null,
      revengeTrade: false,
      exitedEarly: false,
      missedDueToHesitation: false,
      commission: 5.0,
      riskAmount: 1000,
      rewardAmount: 2000,
      winRate: 0,
    },
  ]

  // Add 25 more generated trades (days 6-30)
  const generatedTrades = generate30DaysTrades().slice(5) // Skip first 5 days (we have manual ones)
  const allDemoTrades = [...demoTrades, ...generatedTrades]

  // Generate demo morning checks
  const demoMorningChecks = [
    {
      id: "demo-morning-1",
      date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      sleepQuality: 8,
      sleepHours: 7.5,
      energyLevel: 8,
      stressLevel: 3,
      focus: 8,
      physicalHealth: 9,
      emotionalState: 8,
      exercise: true,
      exerciseMinutes: 30,
      meditation: true,
      meditationMinutes: 15,
      morningRoutine: true,
      hydration: true,
      score: 85,
    },
    {
      id: "demo-morning-2",
      date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      sleepQuality: 6,
      sleepHours: 5.5,
      energyLevel: 5,
      stressLevel: 6,
      focus: 5,
      physicalHealth: 7,
      emotionalState: 5,
      exercise: false,
      exerciseMinutes: 0,
      meditation: false,
      meditationMinutes: 0,
      morningRoutine: false,
      hydration: true,
      score: 58,
    },
    {
      id: "demo-morning-3",
      date: new Date().toISOString().split("T")[0],
      sleepQuality: 9,
      sleepHours: 8,
      energyLevel: 9,
      stressLevel: 2,
      focus: 9,
      physicalHealth: 9,
      emotionalState: 9,
      exercise: true,
      exerciseMinutes: 45,
      meditation: true,
      meditationMinutes: 20,
      morningRoutine: true,
      hydration: true,
      score: 92,
    },
  ];

  // Generate demo gamification data
  const demoGamification = {
    xp: 450,
    level: 3,
    achievements: [
      {
        id: "first-trade",
        name: "První obchod",
        description: "Zaznamenejte svůj první obchod",
        unlocked: true,
        unlockedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "morning-streak-3",
        name: "Ranní rutina - 3 dny",
        description: "Dokončete morning check 3 dny v řadě",
        unlocked: true,
        unlockedAt: new Date().toISOString(),
      },
    ],
    dailyXPLog: {},
  };

  return {
    trades: allDemoTrades,
    morningChecks: demoMorningChecks,
    gamification: demoGamification,
  };
}
